name: Snyk Security

on:
  pull_request:
    branches: [main, refactor-tests-docs]
  push:
    branches:
      - main
      - narrow-crest
      - refactor-tests-docs

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    name: Security audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@8e119fbb6c251787721d34ba683ed48eba792766 # master as of 2026-07-02
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: snyk test --severity-threshold=high --package-manager=cargo
