name: Snyk Security

on:
  pull_request:
    branches: [main, refactor-tests-docs]
  push:
    branches:
      - main
      - narrow-crest
      - refactor-tests-docs

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  audit:
    name: Security audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Install Snyk CLI
        uses: snyk/actions/setup@8e119fbb6c251787721d34ba683ed48eba792766 # master as of 2026-07-02

      - name: Run Snyk to check for Rust vulnerabilities
        run: snyk test --severity-threshold=high --package-manager=cargo
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
